---
# Setup ipv6 rules


- name: Allow established connections
  iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
      action: insert
      ip_version: ipv6
      comment: Allow established connections

- name: Set policy to drop input packets that dont match the ones above
  iptables:
      chain: INPUT
      policy: DROP
      ip_version: ipv6
      comment: Drop input that doesnt match rules

- name: Set policy to drop forward packets
  iptables:
      chain: FORWARD
      policy: DROP
      ip_version: ipv6
      comment: Drop forward
