---
# Setup iptables rules and make them persistent


- include: ipv4.yml
- include: ipv6.yml

- name: Save v4 rules (/etc/sysconfig/iptables)
  shell: iptables-save -c > /etc/sysconfig/iptables

- name: Save v6 rules (/etc/sysconfig/ip6tables)
  shell: ip6tables-save -c > /etc/sysconfig/ip6tables

- name: Ensure iptables service is installed
  yum: 
    name: iptables-services 
    state: present
  when: ansible_distribution_major_version >= '7'

- name: Ensure iptables service is installed
  yum: 
    name: iptables 
    state: present
  when: ansible_distribution_major_version < '7'

- name: Ensure iptables service is enabled & started
  service: 
    name: iptables 
    enabled: yes 
    state: started

- name: Ensure ip6tables service is enabled & started
  service: 
    name: ip6tables 
    enabled: yes 
    state: started

